dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  make test
after_success:
  coveralls
